export const mockStates = [
  { value: 35, label: "Andaman And Nicobar Islands" },
  { value: 28, label: "Andhra Pradesh" },
  { value: 12, label: "Arunachal Pradesh" },
  { value: 18, label: "Assam" },
  { value: 10, label: "Bihar" },
  { value: 4, label: "Chandigarh" },
  { value: 22, label: "Chhattisgarh" },
  { value: 7, label: "Delhi" },
  { value: 30, label: "Goa" },
  { value: 24, label: "Gujarat" },
  { value: 6, label: "Haryana" },
  { value: 2, label: "Himachal Pradesh" },
  { value: 1, label: "Jammu And Kashmir" },
  { value: 20, label: "Jharkhand" },
  { value: 29, label: "Karnataka" },
  { value: 32, label: "Kerala" },
  { value: 37, label: "Ladakh" },
  { value: 31, label: "Lakshadweep" },
  { value: 23, label: "Madhya Pradesh" },
  { value: 27, label: "Maharashtra" },
  { value: 14, label: "Manipur" },
  { value: 17, label: "Meghalaya" },
  { value: 15, label: "Mizoram" },
  { value: 13, label: "Nagaland" },
  { value: 21, label: "Odisha" },
  { value: 34, label: "Puducherry" },
  { value: 3, label: "Punjab" },
  { value: 8, label: "Rajasthan" },
  { value: 11, label: "Sikkim" },
  { value: 33, label: "Tamil Nadu" },
  { value: 36, label: "Telangana" },
  { value: 38, label: "The Dadra And Nagar Haveli And Daman And Diu" },
  { value: 16, label: "Tripura" },
  { value: 5, label: "Uttarakhand" },
  { value: 9, label: "Uttar Pradesh" },
  { value: 19, label: "West Bengal" },
];
